-- MySQL Script generated by MySQL Workbench
-- Tue 18 Oct 2022 09:26:27 AM +03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema airport
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `airport` ;

-- -----------------------------------------------------
-- Schema airport
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airport` ;
USE `airport` ;

-- -----------------------------------------------------
-- Table `airport`.`airports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airport`.`airports` ;

CREATE TABLE IF NOT EXISTS `airport`.`airports` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `airport_name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`aircarriers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airport`.`aircarriers` ;

CREATE TABLE IF NOT EXISTS `airport`.`aircarriers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `aircarrier_name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`pilots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airport`.`pilots` ;

CREATE TABLE IF NOT EXISTS `airport`.`pilots` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `aircarrier_id` BIGINT UNSIGNED NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pilots_air_carrier1_idx` (`aircarrier_id` ASC) VISIBLE,
  CONSTRAINT `fk_pilots_air_carrier1`
    FOREIGN KEY (`aircarrier_id`)
    REFERENCES `airport`.`aircarriers` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`passports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airport`.`passports` ;

CREATE TABLE IF NOT EXISTS `airport`.`passports` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `number` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`passengers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airport`.`passengers` ;

CREATE TABLE IF NOT EXISTS `airport`.`passengers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `passport_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_passengers_passports1_idx` (`passport_id` ASC) VISIBLE,
  CONSTRAINT `fk_passengers_passports1`
    FOREIGN KEY (`passport_id`)
    REFERENCES `airport`.`passports` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`directions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airport`.`directions` ;

CREATE TABLE IF NOT EXISTS `airport`.`directions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(50) NOT NULL,
  `distance` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `country_UNIQUE` (`country` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`aircrafts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airport`.`aircrafts` ;

CREATE TABLE IF NOT EXISTS `airport`.`aircrafts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `aircarrier_id` BIGINT UNSIGNED NULL,
  `number` BIGINT UNSIGNED NOT NULL,
  `model` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `aircraft_number_UNIQUE` (`number` ASC) VISIBLE,
  INDEX `fk_aircrafts_air_carrier1_idx` (`aircarrier_id` ASC) VISIBLE,
  CONSTRAINT `fk_aircraft_air_carrier1`
    FOREIGN KEY (`aircarrier_id`)
    REFERENCES `airport`.`aircarriers` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`airstrips`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airport`.`airstrips` ;

CREATE TABLE IF NOT EXISTS `airport`.`airstrips` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `airport_id` BIGINT UNSIGNED NOT NULL,
  `number` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_airstrip_airports1_idx` (`airport_id` ASC) VISIBLE,
  CONSTRAINT `fk_airstrip_airports1`
    FOREIGN KEY (`airport_id`)
    REFERENCES `airport`.`airports` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`flights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airport`.`flights` ;

CREATE TABLE IF NOT EXISTS `airport`.`flights` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `aircarrier_id` BIGINT UNSIGNED NULL,
  `aircraft_id` BIGINT UNSIGNED NULL,
  `pilot_id` BIGINT UNSIGNED NULL,
  `direction_id` BIGINT UNSIGNED NULL,
  `airstrip_id` BIGINT UNSIGNED NULL,
  `number` BIGINT UNSIGNED NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `flight_number_UNIQUE` (`number` ASC) VISIBLE,
  INDEX `fk_flights_aircrafts1_idx` (`aircraft_id` ASC) VISIBLE,
  INDEX `fk_flights_airstrip1_idx` (`airstrip_id` ASC) VISIBLE,
  INDEX `fk_flights_aircarriers1_idx` (`aircarrier_id` ASC) VISIBLE,
  INDEX `fk_flights_pilots1_idx` (`pilot_id` ASC) VISIBLE,
  INDEX `fk_flights_directions1_idx` (`direction_id` ASC) VISIBLE,
  CONSTRAINT `fk_flights_directions1`
    FOREIGN KEY (`direction_id`)
    REFERENCES `airport`.`directions` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flights_aircrafts1`
    FOREIGN KEY (`aircraft_id`)
    REFERENCES `airport`.`aircrafts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flights_airstrip1`
    FOREIGN KEY (`airstrip_id`)
    REFERENCES `airport`.`airstrips` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flights_aircarriers1`
    FOREIGN KEY (`aircarrier_id`)
    REFERENCES `airport`.`aircarriers` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flights_pilots1`
    FOREIGN KEY (`pilot_id`)
    REFERENCES `airport`.`pilots` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`tickets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airport`.`tickets` ;

CREATE TABLE IF NOT EXISTS `airport`.`tickets` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `flight_id` BIGINT UNSIGNED NOT NULL,
  `passenger_id` BIGINT UNSIGNED NOT NULL,
  `price` BIGINT UNSIGNED NOT NULL,
  `seat` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tickets_passengers1_idx` (`passenger_id` ASC) VISIBLE,
  INDEX `fk_tickets_flights1_idx` (`flight_id` ASC) VISIBLE,
  CONSTRAINT `fk_tickets_passengers1`
    FOREIGN KEY (`passenger_id`)
    REFERENCES `airport`.`passengers` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_flights1`
    FOREIGN KEY (`flight_id`)
    REFERENCES `airport`.`flights` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`airport_aircarriers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airport`.`airport_aircarriers` ;

CREATE TABLE IF NOT EXISTS `airport`.`airport_aircarriers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `airport_id` BIGINT UNSIGNED NULL,
  `aircarrier_id` BIGINT UNSIGNED NULL,
  INDEX `fk_aircarriers_has_airports_airports1_idx` (`airport_id` ASC) VISIBLE,
  INDEX `fk_aircarriers_has_airports_aircarriers1_idx` (`aircarrier_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_aircarriers_has_airports_aircarriers1`
    FOREIGN KEY (`aircarrier_id`)
    REFERENCES `airport`.`aircarriers` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aircarriers_has_airports_airports1`
    FOREIGN KEY (`airport_id`)
    REFERENCES `airport`.`airports` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



use airport;

insert into aircarriers(name) values ('Belavia'), ('Aeroflot'), ('Wizzair'), ('Ryanair');

insert into aircrafts(aircarrier_id, number, model) values (1, 1101, 'Boeing');
insert into aircrafts(aircarrier_id, number, model) values (2, 2201, 'Airbus');
insert into aircrafts(aircarrier_id, number, model) values (3, 3301, 'Boeing');
insert into aircrafts(aircarrier_id, number, model) values (4, 4401, 'Airbus');
insert into aircrafts(aircarrier_id, number, model) values (1, 1102, 'Embraer');
insert into aircrafts(aircarrier_id, number, model) values (2, 2202, 'Embraer');
insert into aircrafts(aircarrier_id, number, model) values (3, 3302, 'Embraer');
insert into aircrafts(aircarrier_id, number, model) values (4, 4402, 'Embraer');
insert into aircrafts(aircarrier_id, number, model) values (1, 1103, 'TU');
insert into aircrafts(aircarrier_id, number, model) values (2, 2203, 'SU');
insert into aircrafts(aircarrier_id, number, model) values (3, 3303, 'TU');
insert into aircrafts(aircarrier_id, number, model) values (4, 4403, 'IL');

insert into airports(name) values ('Minsk1'), ('Minsk2');

insert into airstrips(airport_id, number) values (1, 1);
insert into airstrips(airport_id, number) values (1, 2);
insert into airstrips(airport_id, number) values (2, 1);
insert into airstrips(airport_id, number) values (2, 2);

insert into directions(country, distance) values ('Poland', 1000), ('France', 2000), ('Japan', 9000), ('USA', 10000);

insert into airport_aircarriers(airport_id, aircarrier_id) values (1, 1);
insert into airport_aircarriers(airport_id, aircarrier_id) values (1, 2);
insert into airport_aircarriers(airport_id, aircarrier_id) values (2, 3);
insert into airport_aircarriers(airport_id, aircarrier_id) values (2, 4);

insert into pilots(aircarrier_id, name) values (1, 'Igor');
insert into pilots(aircarrier_id, name) values (1, 'Ivan');
insert into pilots(aircarrier_id, name) values (2, 'Max');
insert into pilots(aircarrier_id, name) values (2, 'Petr');
insert into pilots(aircarrier_id, name) values (3, 'Mihail');
insert into pilots(aircarrier_id, name) values (3, 'Oleg');
insert into pilots(aircarrier_id, name) values (4, 'Dima');
insert into pilots(aircarrier_id, name) values (4, 'Alex');

insert into passports(number) values (1234561);
insert into passports(number) values (1234562);
insert into passports(number) values (1234563);
insert into passports(number) values (1234564);
insert into passports(number) values (1234565);
insert into passports(number) values (1234566);
insert into passports(number) values (1234567);
insert into passports(number) values (1234568);

insert into passengers(name, passport_id) values ('Ivan', 1);
insert into passengers(name, passport_id) values ('Oleg', 2);
insert into passengers(name, passport_id) values ('Olga', 3);
insert into passengers(name, passport_id) values ('Anna', 4);
insert into passengers(name, passport_id) values ('Petr', 5);
insert into passengers(name, passport_id) values ('Denis', 6);
insert into passengers(name, passport_id) values ('Zina', 7);
insert into passengers(name, passport_id) values ('Alex', 8);

insert into flights(aircarrier_id, aircraft_id, airstrip_id, direction_id, pilot_id, number, date) values (1, 1, 1, 1, 1, 101, '2022-09-11');
insert into flights(aircarrier_id, aircraft_id, airstrip_id, direction_id, pilot_id, number, date) values (2, 2, 2, 2, 2, 102, '2022-09-12');
insert into flights(aircarrier_id, aircraft_id, airstrip_id, direction_id, pilot_id, number, date) values (3, 3, 3, 3, 3, 103, '2022-09-13');
insert into flights(aircarrier_id, aircraft_id, airstrip_id, direction_id, pilot_id, number, date) values (4, 4, 4, 4, 4, 104, '2022-09-14');


insert into tickets(flight_id, passenger_id, price, seat) values (1, 1, 1100, 11);
insert into tickets(flight_id, passenger_id, price, seat) values (1, 2, 1100, 12);
insert into tickets(flight_id, passenger_id, price, seat) values (2, 3, 1200, 22);
insert into tickets(flight_id, passenger_id, price, seat) values (2, 4, 1200, 23);
insert into tickets(flight_id, passenger_id, price, seat) values (3, 5, 1300, 31);
insert into tickets(flight_id, passenger_id, price, seat) values (3, 6, 1300, 32);
insert into tickets(flight_id, passenger_id, price, seat) values (4, 7, 1400, 44);
insert into tickets(flight_id, passenger_id, price, seat) values (4, 8, 1400, 45);




